\begin{frame}{Introduction}
  Python gère les erreurs avec la structure de contrôle \texttt{try}/\texttt{except} et une hiérarchie de classes d'erreur.
\end{frame}

\begin{frame}{Hiérarchie d'erreurs natives}
  La \bluelink{https://docs.python.org/3/library/exceptions.html\#exception-hierarchy}{documentation officielle} contient une liste complète.
\end{frame}

\begin{frame}{Capturer une erreur}
  \mintedcustom{python/basics/exceptions/try-except}{py}{text}
\end{frame}

\begin{frame}{Définir une erreur personnalisée}
  Peuvent hériter d'\texttt{Exception} ou d'une erreur plus précise.
  \mintedpycode{python/basics/exceptions/custom-exception}
\end{frame}

\begin{frame}{Re-lancer une erreur}
  \mintedcustom{python/basics/exceptions/reraise}{py}{text}
\end{frame}

\begin{frame}{Envelopper des erreurs}
  \mintedcustom{python/basics/exceptions/chain}{py}{text}
\end{frame}

\begin{frame}{\texttt{finally}}
  Le mot-clef \texttt{finally} permet d'exécuter des instructions quoi qu'il arrive.

  La \bluelink{https://docs.python.org/fr/3/reference/compound_stmts.html\#finally}{documentation officielle} contient plus de détails sur cette structure.

  \mintedcustom{python/basics/exceptions/finally}{py}{text}
\end{frame}

\begin{frame}{\texttt{else}}
  Comme pour les boucles, la clause \texttt{else} est exécutée si on sort normalement du \texttt{try}/\texttt{except} (sans passer par le \texttt{except}).
\end{frame}
